# Nombre del workflow
name: Actualizar Repositorios con Más Forks

# Cuándo se ejecutará
on:
  # Se ejecutará cada vez que se haga un push a la rama 'main'
  push:
    branches: [ main ]
  # Se ejecutará una vez al día a medianoche (UTC)
  schedule:
    - cron: '0 0 * * *'
  # También permite ejecutarlo manualmente desde la pestaña de Actions
  workflow_dispatch:

# Permisos necesarios para que el workflow pueda modificar el repositorio
permissions:
  contents: write

# Tareas a realizar
jobs:
  update-most-forked:
    runs-on: ubuntu-latest # Se ejecutará en una máquina virtual con Ubuntu

    steps:
      # 1. Descargar el contenido del repositorio
      - name: Descargar repositorio
        uses: actions/checkout@v4

      # 2. Generar y actualizar el README
      - name: Actualizar README con los repos más bifurcados
        env:
          # Token de autenticación para usar la API de GitHub
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Obtiene el nombre de usuario del repositorio automáticamente
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          echo "🔍 Buscando los repositorios con más forks para el usuario $REPO_OWNER..."

          # Obtener la lista de los 3 repos más bifurcados usando la CLI de GitHub y jq
          REPOS=$(gh repo list $REPO_OWNER --limit 1000 --json nameWithOwner,forks | jq -r 'sort_by(.forks) | reverse | .[0:3] | .[].nameWithOwner')

          # Construir el contenido en Markdown
          MARKDOWN=""
          for REPO_FULL_NAME in $REPOS; do
            MARKDOWN+="  <a href=\"https://github.com/$REPO_FULL_NAME\">\n"
            MARKDOWN+="    <img src=\"https://github-readme-stats.vercel.app/api/pin/?username=$REPO_OWNER&repo=$(basename $REPO_FULL_NAME)&theme=radical\" alt=\"$(basename $REPO_FULL_NAME)\" />\n"
            MARKDOWN+="  </a>\n"
          done

          echo "✅ Markdown generado:"
          echo "$MARKDOWN"

          # Eliminar la sección antigua del README
          sed -i '/<!-- START_SECTION:forked-repos -->/,/<!-- END_SECTION:forked-repos -->/d' README.md

          # Encontrar la línea del encabezado para insertar el nuevo contenido después de ella
          HEADER_LINE=$(grep -n "## Proyectos Destacados (Forks) 🌟" README.md | cut -d: -f1)

          # Insertar el nuevo contenido en el README
          sed -i "${HEADER_LINE}a \\\n<!-- START_SECTION:forked-repos -->\\\n<div align=\"center\">\\\n$MARKDOWN\\\n</div>\\\n<!-- END_SECTION:forked-repos -->" README.md

      # 3. Guardar y subir los cambios
      - name: Commit y Push de los cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          # Solo hace commit si hay cambios para evitar commits vacíos
          git diff --staged --quiet || git commit -m "🔄 Auto-update: lista de repos con más forks"
          git push
